use_frameworks!

target 'LTRequest_Example' do
  pod 'LTRequest', :path => '../'

  target 'LTRequest_Tests' do
    inherit! :search_paths


  end

#pod "LTRequest",:git => 'git@github.com:yelon21/LTRequest.git'
end
